### ISSUE TITLE
error using sync block

### ISSUE THREAD

**Issue by JaymeNeto** [pothosware/PothosSoapy#20]
Hi I'm new on pothos and I'm having a problem for using the sync block. I need to transmit a chirp signal using a usrp. Does anyone now how to fix it?
![captura de tela 6](https://user-images.githubusercontent.com/25558078/40621997-c434ce1c-6275-11e8-867e-fc8c5f9bd857.png)

**Comment by guruofquality** [comment]
Make sure you can talk to the device first: https://github.com/pothosware/PothosSoapy/wiki/Tutorial#device-arguments

type:usrp will probably prevent uhd from matching any devices

**Comment by JaymeNeto** [comment]
But do you mean any device with is not an USRP?

**Comment by guruofquality** [comment]
Try out the args with some of the command line tools first, uhd_find_devices and SoapySDRUtil. Technically that box should turn into a dropdown with available devices, so I dont think your system sees any usrp anyway.

But the `type` keyword is specially used in uhd to filter for specific devices like type=b200, so I think type=usrp will filter out all devices supported in uhd deiver because a device with type usrp does not exist.
